name: CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v**'
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install jsonnet, jsonnet-bundler and grafana/plugin-validator
      run: |
        go get github.com/google/go-jsonnet/cmd/jsonnet
        go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
        go get github.com/grafana/plugin-validator/cmd/plugincheck
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: make deps

    - name: Test plugin
      run: make test-frontend-coverage test-backend-coverage

    - name: Build plugin
      run: make build

    - name: Create plugin zip file
      run: make zip

    - name: Run linters
      run: make lint
      # ignore unsigned plugin error in CI
      continue-on-error: true

    - name: Publish build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
