name: End-to-End tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v**'
  pull_request:

jobs:
  e2e:
    name: End-to-End tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install dependencies
      run: make deps-frontend

    - name: Run End-to-End tests
      run: make test-e2e
