name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install jsonnet, jsonnet-bundler and grafana/plugin-validator
      run: |
        go get github.com/google/go-jsonnet/cmd/jsonnet
        go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
        go get github.com/grafana/plugin-validator/cmd/plugincheck
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: make deps

    - name: Test backend
      run: make test-backend

    - name: Test frontend & Build plugin
      run: make build

    - name: Check if package version and git tag matches
      run: |
        if [ "v$(jq -r '.info.version' dist/plugin.json)" != "${GITHUB_REF#refs/*/}" ]; then
          echo "Plugin version doesn't match git tag"
          exit 1
        fi

    - name: Sign plugin
      run: make sign
      env:
        GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}

    - name: Create plugin zip file
      run: make zip

    - name: Run linters
      run: make lint
      # ignore unsigned plugin error
      continue-on-error: true

    - name: Create GitHub release
      run: ci/scripts/github-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
